steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg
      - VITE_API_URL=https://relaypay-dev-api-845745374775.us-central1.run.app
      - -t
      - us-central1-docker.pkg.dev/voiceagentproject-494309/relaypay-dev-images/frontend:latest
      - .
images:
  - 'us-central1-docker.pkg.dev/voiceagentproject-494309/relaypay-dev-images/frontend:latest'
